#!/usr/bin/env python3
"""Build the frozen wide-scan cost inputs from public daily market data.

This script deliberately reads only adjusted daily OHLCV. It never runs a strategy,
reads a strategy result, or calls OpenD, so running it cannot spend Moomoo history
quota or leak wide-scan returns into the universe/cost decision.

The output is an audit table, not a claim that bar data reveal the true spread. The
all-in round-trip heuristic is fixed in docs/wide_scan_methodology.md and combines:
one minimum tick at the median price, an inverse-dollar-volume penalty, and a fixed
execution/model-risk buffer. Values are rounded upward to 0.5 bps.
"""
from __future__ import annotations

import argparse
import csv
import math
from pathlib import Path

import pandas as pd
import yfinance as yf

DEFAULT_START = "2025-09-17"
DEFAULT_END_EXCLUSIVE = "2026-09-16"
MIN_SESSIONS = 225
MIN_MEDIAN_PRICE = 5.0
MIN_MEDIAN_DOLLAR_VOLUME = 25_000_000.0

EXECUTION_BUFFER_BPS = 1.25
LIQUIDITY_REFERENCE_DOLLARS = 5_000_000_000.0
LIQUIDITY_OFFSET = 0.40
MIN_COST_BPS = 1.5
MAX_COST_BPS = 12.0
ROUNDING_BPS = 0.5


def estimate_round_trip_bps(median_price: float, median_dollar_volume: float) -> dict[str, float]:
    """Return the frozen heuristic's components and pessimistically rounded cost."""
    if median_price <= 0 or median_dollar_volume <= 0:
        raise ValueError("price and dollar volume must be positive")

    tick_bps = 100.0 / median_price  # $0.01 / price * 10,000
    liquidity_penalty_bps = max(
        0.0,
        math.sqrt(LIQUIDITY_REFERENCE_DOLLARS / median_dollar_volume) - LIQUIDITY_OFFSET,
    )
    raw_bps = EXECUTION_BUFFER_BPS + tick_bps + liquidity_penalty_bps
    rounded_bps = math.ceil(raw_bps / ROUNDING_BPS) * ROUNDING_BPS
    cost_bps = min(MAX_COST_BPS, max(MIN_COST_BPS, rounded_bps))
    return {
        "tick_bps": tick_bps,
        "liquidity_penalty_bps": liquidity_penalty_bps,
        "raw_bps": raw_bps,
        "round_trip_bps": cost_bps,
    }


def read_universe(path: Path) -> list[dict[str, str]]:
    with path.open(newline="") as handle:
        rows = list(csv.DictReader(handle))
    if len(rows) != 97:
        raise ValueError(f"expected 97 universe rows, found {len(rows)}")
    if len({row["symbol"] for row in rows}) != len(rows):
        raise ValueError("universe contains duplicate symbols")
    return rows


def download_daily(ticker: str, start: str, end_exclusive: str) -> pd.DataFrame:
    frame = yf.download(
        ticker,
        start=start,
        end=end_exclusive,
        interval="1d",
        auto_adjust=True,
        actions=False,
        progress=False,
        threads=False,
    )
    if isinstance(frame.columns, pd.MultiIndex):
        frame = frame.xs(ticker, axis=1, level="Ticker")
    required = ["Close", "Volume"]
    if frame.empty or any(column not in frame for column in required):
        raise RuntimeError(f"no usable daily data returned for {ticker}")
    return frame[required].dropna()


def build_row(spec: dict[str, str], frame: pd.DataFrame, start: str, end_exclusive: str) -> dict:
    median_price = float(frame["Close"].median())
    median_volume = float(frame["Volume"].median())
    median_dollar_volume = float((frame["Close"] * frame["Volume"]).median())
    parts = estimate_round_trip_bps(median_price, median_dollar_volume)
    sessions = len(frame)
    screen_pass = (
        sessions >= MIN_SESSIONS
        and median_price >= MIN_MEDIAN_PRICE
        and median_dollar_volume >= MIN_MEDIAN_DOLLAR_VOLUME
    )
    return {
        **spec,
        "window_start": start,
        "window_end_inclusive": str(frame.index.max().date()),
        "sessions": sessions,
        "median_price": round(median_price, 4),
        "median_daily_volume": round(median_volume),
        "median_dollar_volume": round(median_dollar_volume),
        "tick_bps": round(parts["tick_bps"], 4),
        "liquidity_penalty_bps": round(parts["liquidity_penalty_bps"], 4),
        "execution_buffer_bps": EXECUTION_BUFFER_BPS,
        "raw_bps": round(parts["raw_bps"], 4),
        "round_trip_bps": parts["round_trip_bps"],
        "screen_pass": screen_pass,
        "requested_end_exclusive": end_exclusive,
    }


def render_runtime_table(rows: pd.DataFrame, path: Path) -> None:
    """Write the reviewed CSV values as an importable, dependency-free runtime table."""
    lines = [
        '"""Generated by scripts/build_wide_scan_costs.py; do not edit by hand."""',
        "",
        "WIDE_SCAN_ROUND_TRIP_BPS: dict[str, float] = {",
    ]
    for row in rows.sort_values("slot").itertuples():
        lines.append(f'    "{row.symbol}": {float(row.round_trip_bps):.1f},')
    lines.extend(["}", ""])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--universe", type=Path, default=Path("docs/wide_scan_universe.csv"))
    parser.add_argument("--output", type=Path, default=Path("docs/wide_scan_cost_inputs.csv"))
    parser.add_argument(
        "--runtime-output", type=Path, default=Path("mm/wide_scan_cost_table.py")
    )
    parser.add_argument("--start", default=DEFAULT_START)
    parser.add_argument("--end-exclusive", default=DEFAULT_END_EXCLUSIVE)
    args = parser.parse_args()

    rows = []
    failures = []
    for spec in read_universe(args.universe):
        try:
            frame = download_daily(spec["ticker"], args.start, args.end_exclusive)
            row = build_row(spec, frame, args.start, args.end_exclusive)
            rows.append(row)
            print(
                f"{spec['ticker']:5} {row['sessions']:3} sessions  "
                f"${row['median_dollar_volume'] / 1e9:6.2f}B/day  "
                f"cost={row['round_trip_bps']:4.1f} bps  "
                f"screen={'PASS' if row['screen_pass'] else 'FAIL'}"
            )
        except Exception as exc:  # preserve a complete failure list for a one-shot universe
            failures.append((spec["ticker"], str(exc)))
            print(f"{spec['ticker']:5} FAILED: {exc}")

    if failures:
        detail = "; ".join(f"{ticker}: {message}" for ticker, message in failures)
        raise SystemExit(f"refusing partial output; {len(failures)} downloads failed: {detail}")

    output = pd.DataFrame(rows).sort_values("slot", key=lambda col: col.astype(int))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    output.to_csv(args.output, index=False)
    render_runtime_table(output, args.runtime_output)
    failed_screen = output.loc[~output["screen_pass"], "ticker"].tolist()
    print(f"\nwrote {len(output)} frozen input rows to {args.output}")
    print(f"wrote runtime table to {args.runtime_output}")
    if failed_screen:
        print("liquidity screen failures: " + ", ".join(failed_screen))


if __name__ == "__main__":
    main()
